services:
  postgres:
    image: postgres:16-alpine
    container_name: portal-uala-bank-postgres
    environment:
      POSTGRES_DB: portal_uala_bank
      POSTGRES_USER: portal
      POSTGRES_PASSWORD: portal
    ports:
      - "9432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
